# Generated by Django 5.2.6 on 2025-09-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id_estado_venta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_venta',
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id_orden_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('id_estado_venta', models.ForeignKey(db_column='id_estado_venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.estadoventa')),
            ],
            options={
                'db_table': 'orden_venta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='ventas.empresa')),
                ('id_orden_venta', models.OneToOneField(db_column='id_orden_venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='OrdenVentaProducto',
            fields=[
                ('id_orden_venta_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_orden_venta', models.ForeignKey(db_column='id_orden_venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'orden_venta_producto',
                'unique_together': {('id_orden_venta', 'id_producto')},
            },
        ),
    ]
