# Generated by Django 5.2.6 on 2025-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='prioridad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
