# Generated by Django 5.2.6 on 2025-09-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ordenventa_fecha_entrega_ordenventa_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='prioridad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
