# Generated by Django 5.2.6 on 2025-10-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_ordenventa_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prioridad',
            },
        ),
        migrations.RemoveField(
            model_name='ordenventa',
            name='prioridad',
        ),
    ]
