# Generated by Django 5.2.6 on 2025-10-01 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_prioridad_remove_ordenventa_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='id_prioridad',
            field=models.ForeignKey(db_column='id_prioridad', default=2, on_delete=django.db.models.deletion.CASCADE, to='ventas.prioridad'),
            preserve_default=False,
        ),
    ]
