# Generated by Django 5.2.6 on 2025-10-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_ordenventa_id_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioridad',
            name='descripcion',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
