# Generated by Django 5.2.6 on 2025-10-10 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_prioridad_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
