# Generated by Django 5.2.6 on 2025-10-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_factura_id_empresa_delete_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
