# Generated by Django 5.2.6 on 2025-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_ordenventa_fecha_estimada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id_direccion_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=200)),
                ('altura', models.CharField(help_text='Número de la casa, piso, dpto, etc.', max_length=50)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'direccion_cliente',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(blank=True, help_text='Campo para contraseña (almacenamiento inseguro)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuil',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
