# Generated by Django 5.2.6 on 2025-10-18 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_direccioncliente_cliente_apellido_cliente_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccioncliente',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='ventas.cliente'),
            preserve_default=False,
        ),
    ]
