# Generated by Django 5.2.6 on 2025-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_direccioncliente_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='altura',
            field=models.CharField(blank=True, help_text='Número de la casa, piso, dpto, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='tipo_venta',
            field=models.CharField(choices=[('EMP', 'Empleado'), ('ONL', 'Online')], default='EMP', max_length=3, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='zona',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
