# Generated by Django 5.2.6 on 2025-10-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_ordenventa_altura_ordenventa_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenventa',
            name='zona',
            field=models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur'), ('E', 'Este'), ('O', 'Oeste')], max_length=10, null=True),
        ),
    ]
