# Generated by Django 5.2.6 on 2025-10-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_ordenventa_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_prioridad',
            field=models.ForeignKey(blank=True, db_column='id_prioridad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.prioridad'),
        ),
    ]
