# Generated by Django 5.2.6 on 2025-10-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_rol_permisos'),
        ('ventas', '0013_cliente_id_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenventa',
            name='id_empleado',
            field=models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
