# Generated by Django 5.2.6 on 2025-10-22 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_ordenventa_id_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reclamo', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='Abierto', max_length=50)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
            options={
                'db_table': 'reclamo',
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
            options={
                'db_table': 'sugerencia',
            },
        ),
    ]
