# Generated by Django 5.2.6 on 2025-10-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_reclamo_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='titulo',
            field=models.CharField(default='titulo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
