# Generated by Django 5.2.6 on 2025-10-23 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_reclamo_titulo_sugerencia_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id_nota_credito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('motivo', models.TextField(blank=True, help_text='Razón de la nota de crédito (ej. Devolución)', null=True)),
                ('id_factura', models.OneToOneField(db_column='id_factura', help_text='Factura que esta nota de crédito anula.', on_delete=django.db.models.deletion.CASCADE, to='ventas.factura')),
            ],
            options={
                'db_table': 'nota_credito',
            },
        ),
    ]
