# Generated by Django 5.2.6 on 2025-10-23 23:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_rol_permisos'),
        ('ventas', '0017_notacredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotaCredito',
            fields=[
                ('id_nota_credito', models.IntegerField(blank=True, db_index=True)),
                ('fecha', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('motivo', models.TextField(blank=True, help_text='Razón de la nota de crédito (ej. Devolución)', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_factura', models.ForeignKey(blank=True, db_column='id_factura', db_constraint=False, help_text='Factura que esta nota de crédito anula.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.factura')),
            ],
            options={
                'verbose_name': 'historical nota credito',
                'verbose_name_plural': 'historical nota creditos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrdenVenta',
            fields=[
                ('id_orden_venta', models.IntegerField(blank=True, db_index=True)),
                ('fecha', models.DateTimeField(blank=True, editable=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True)),
                ('tipo_venta', models.CharField(choices=[('EMP', 'Empleado'), ('ONL', 'Online')], default='EMP', max_length=3, verbose_name='Tipo de Venta')),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('altura', models.CharField(blank=True, help_text='Número de la casa, piso, dpto, etc.', max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, choices=[('N', 'Norte'), ('S', 'Sur'), ('E', 'Este'), ('O', 'Oeste')], max_length=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.cliente')),
                ('id_empleado', models.ForeignKey(blank=True, db_column='id_empleado', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('id_estado_venta', models.ForeignKey(blank=True, db_column='id_estado_venta', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.estadoventa')),
                ('id_prioridad', models.ForeignKey(blank=True, db_column='id_prioridad', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.prioridad')),
            ],
            options={
                'verbose_name': 'historical orden venta',
                'verbose_name_plural': 'historical orden ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
