# Generated by Django 5.2.6 on 2025-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_cliente_altura_cliente_calle_cliente_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenventa',
            name='fecha_entrega_planificada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenventa',
            name='fecha_entrega_planificada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
