# Generated by Django 5.2.6 on 2025-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clave', models.CharField(help_text='Clave única para identificar la variable (e.g., HORAS_LABORABLES_POR_DIA)', max_length=100, unique=True, verbose_name='Nombre de la Variable (Clave)')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, help_text='Para qué se usa esta variable.', verbose_name='Descripción')),
                ('tipo_dato', models.CharField(default='int', help_text="Ayuda a convertir el 'valor' al tipo correcto en Python.", max_length=20, verbose_name='Tipo de Dato Esperado')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
