# Generated by Django 5.2.6 on 2025-10-23 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0016_reclamo_titulo_sugerencia_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id_estado_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_despacho',
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'repartidor',
            },
        ),
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id_orden_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('id_estado_despacho', models.ForeignKey(blank=True, db_column='id_estado_despacho', null=True, on_delete=django.db.models.deletion.SET_NULL, to='despachos.estadodespacho')),
                ('id_repartidor', models.ForeignKey(blank=True, db_column='id_repartidor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='despachos.repartidor')),
            ],
            options={
                'db_table': 'orden_despacho',
            },
        ),
        migrations.CreateModel(
            name='DespachoOrenVenta',
            fields=[
                ('id_despacho_orden_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_orden_venta', models.ForeignKey(db_column='id_orden_venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
                ('id_estado_despacho', models.ForeignKey(blank=True, db_column='id_estado_despacho', null=True, on_delete=django.db.models.deletion.SET_NULL, to='despachos.estadodespacho')),
                ('id_orden_despacho', models.ForeignKey(db_column='id_orden_despacho', on_delete=django.db.models.deletion.CASCADE, to='despachos.ordendespacho')),
            ],
            options={
                'db_table': 'despacho_orden_venta',
            },
        ),
    ]
