# Generated by Django 5.2.6 on 2025-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0002_historicalordendespacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartidor',
            name='patenete',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
