# Generated by Django 5.2.6 on 2025-10-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0003_repartidor_patenete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartidor',
            old_name='patenete',
            new_name='patente',
        ),
    ]
