# Generated by Django 5.2.6 on 2025-10-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias_primas', '0001_initial'),
        ('productos', '0002_producto_dias_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLoteMateriaPrima',
            fields=[
                ('id_estado_lote_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_lote_materia_prima',
            },
        ),
        migrations.CreateModel(
            name='EstadoLoteProduccion',
            fields=[
                ('id_estado_lote_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_lote_produccion',
            },
        ),
        migrations.CreateModel(
            name='LoteMateriaPrima',
            fields=[
                ('id_lote_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('id_estado_lote_materia_prima', models.ForeignKey(db_column='id_estado_lote_materia_prima', on_delete=django.db.models.deletion.CASCADE, to='stock.estadolotemateriaprima')),
                ('id_materia_prima', models.ForeignKey(db_column='id_materia_prima', on_delete=django.db.models.deletion.CASCADE, to='materias_primas.materiaprima')),
            ],
            options={
                'db_table': 'lote_materia_prima',
            },
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id_lote_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_produccion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('id_estado_lote_produccion', models.ForeignKey(db_column='id_estado_lote_produccion', on_delete=django.db.models.deletion.CASCADE, to='stock.estadoloteproduccion')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'lote_produccion',
            },
        ),
        migrations.CreateModel(
            name='LoteProduccionMateria',
            fields=[
                ('id_lote_produccion_materia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.IntegerField()),
                ('id_lote_materia_prima', models.ForeignKey(db_column='id_lote_materia_prima', on_delete=django.db.models.deletion.CASCADE, to='stock.lotemateriaprima')),
                ('id_lote_produccion', models.ForeignKey(db_column='id_lote_produccion', on_delete=django.db.models.deletion.CASCADE, to='stock.loteproduccion')),
            ],
            options={
                'db_table': 'lote_produccion_materia',
            },
        ),
    ]
