# Generated by Django 5.2.6 on 2025-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotemateriaprima',
            name='cantidad_reservada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='cantidad_reservada',
            field=models.IntegerField(default=0),
        ),
    ]
