# Generated by Django 5.2.6 on 2025-10-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_lotemateriaprima_cantidad_reservada_and_more'),
        ('ventas', '0008_ordenventa_fecha_estimada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteproduccion',
            name='cantidad_reservada',
        ),
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_reservada', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('id_lote_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='stock.loteproduccion')),
                ('id_orden_venta_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='ventas.ordenventaproducto')),
            ],
            options={
                'db_table': 'reserva_stock',
                'unique_together': {('id_orden_venta_producto', 'id_lote_produccion')},
            },
        ),
    ]
