# Generated by Django 5.2.6 on 2025-10-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_loteproduccion_cantidad_reservada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_estado_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_reserva',
            },
        ),
        migrations.AlterUniqueTogether(
            name='reservastock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='id_estado_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stock.estadoreserva'),
        ),
    ]
