# Generated by Django 5.2.6 on 2025-10-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_estadoreserva_alter_reservastock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservastock',
            name='id_estado_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.estadoreserva'),
        ),
    ]
