# Generated by Django 5.2.6 on 2025-10-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_ordenproduccion_id_producto'),
        ('stock', '0005_alter_reservastock_id_estado_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReservaMateria',
            fields=[
                ('id_estado_reserva_materia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_reserva_materia',
            },
        ),
        migrations.RemoveField(
            model_name='lotemateriaprima',
            name='cantidad_reservada',
        ),
        migrations.CreateModel(
            name='ReservaMateriaPrima',
            fields=[
                ('id_reserva_materia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_reservada', models.IntegerField()),
                ('id_estado_reserva_materia', models.ForeignKey(db_column='id_estado_reserva_materia', on_delete=django.db.models.deletion.CASCADE, to='stock.estadoreservamateria')),
                ('id_lote_materia_prima', models.ForeignKey(db_column='id_lote_materia_prima', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='stock.lotemateriaprima')),
                ('id_orden_produccion', models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'reserva_materia_prima',
            },
        ),
    ]
