# Generated by Django 5.2.6 on 2025-10-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias_primas', '0001_initial'),
        ('productos', '0002_producto_dias_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'receta',
            },
        ),
        migrations.CreateModel(
            name='RecetaMateriaPrima',
            fields=[
                ('id_receta_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('id_materia_prima', models.ForeignKey(db_column='id_materia_prima', on_delete=django.db.models.deletion.CASCADE, to='materias_primas.materiaprima')),
                ('id_receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'receta_materia_prima',
            },
        ),
    ]
