# Generated by Django 5.2.6 on 2025-10-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_initial'),
        ('productos', '0002_producto_dias_duracion'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLinea',
            fields=[
                ('id_producto_linea', models.AutoField(primary_key=True, serialize=False)),
                ('cant_por_hora', models.IntegerField(blank=True, null=True)),
                ('id_linea_produccion', models.ForeignKey(db_column='id_linea_produccion', on_delete=django.db.models.deletion.CASCADE, to='produccion.lineaproduccion')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'producto_linea',
                'unique_together': {('id_producto', 'id_linea_produccion')},
            },
        ),
    ]
