# Generated by Django 5.2.6 on 2025-11-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_productolinea'),
    ]

    operations = [
        migrations.AddField(
            model_name='productolinea',
            name='cantidad_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
