# Generated by Django 5.2.6 on 2025-09-27 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidad',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_tipo_producto', models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto')),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='productos.unidad')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
