# Generated by Django 5.2.6 on 2025-10-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dias_duracion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
