# Generated by Django 5.2.6 on 2025-10-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_dias_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='umbral_minimo',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
