# Generated by Django 5.2.6 on 2025-10-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_umbral_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_base64', models.TextField(blank=True, help_text='Contenido de la imagen codificado en Base64', null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'db_table': 'imagen_producto',
            },
        ),
    ]
