# Generated by Django 5.2.6 on 2025-11-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_combo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'combo',
            },
        ),
        migrations.CreateModel(
            name='ComboProducto',
            fields=[
                ('id_combo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('id_combo', models.ForeignKey(db_column='id_combo', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.combo')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'combo_producto',
                'unique_together': {('id_combo', 'id_producto')},
            },
        ),
    ]
