# Generated by Django 5.2.6 on 2025-11-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_combo_comboproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
