# Generated by Django 5.2.6 on 2025-11-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_combo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboproducto',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ImagenCombo',
            fields=[
                ('id_imagen_combo', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_base64', models.TextField(blank=True, help_text='Imagen del combo en Base64', null=True)),
                ('id_combo', models.ForeignKey(db_column='id_combo', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.combo')),
            ],
            options={
                'db_table': 'imagen_combo',
            },
        ),
    ]
