# Generated by Django 5.2.6 on 2025-10-04 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_dias_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMateriaPrima',
            fields=[
                ('id_tipo_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_materia_prima',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='productos.unidad')),
                ('id_tipo_materia_prima', models.ForeignKey(db_column='id_tipo_materia_prima', on_delete=django.db.models.deletion.CASCADE, to='materias_primas.tipomateriaprima')),
            ],
            options={
                'db_table': 'materia_prima',
            },
        ),
    ]
