# Generated by Django 5.2.6 on 2025-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias_primas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='umbral_minimo',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
