# Generated by Django 5.2.6 on 2025-10-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias_primas', '0002_materiaprima_umbral_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaprima',
            name='umbral_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
