# Generated by Django 5.2.6 on 2025-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias_primas', '0003_alter_materiaprima_umbral_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_time_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='cantidad_minima_pedido',
            field=models.IntegerField(default=1),
        ),
    ]
