# Generated by Django 5.2.6 on 2025-10-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrdenProduccion',
            fields=[
                ('id_estado_orden_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_orden_produccion',
            },
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id_linea_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'linea_produccion',
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id_no_conformidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('cant_desperdiciada', models.IntegerField()),
            ],
            options={
                'db_table': 'no_conformidades',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('id_estado_orden_produccion', models.ForeignKey(db_column='id_estado_orden_produccion', on_delete=django.db.models.deletion.CASCADE, to='produccion.estadoordenproduccion')),
                ('id_linea_produccion', models.ForeignKey(blank=True, db_column='id_linea_produccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.lineaproduccion')),
            ],
            options={
                'db_table': 'orden_produccion',
            },
        ),
    ]
