# Generated by Django 5.2.6 on 2025-10-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_rol_permisos'),
        ('produccion', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_lote_produccion',
            field=models.ForeignKey(blank=True, db_column='id_lote_produccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.loteproduccion'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_operario',
            field=models.ForeignKey(blank=True, db_column='id_operario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_operadas', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_supervisor',
            field=models.ForeignKey(blank=True, db_column='id_supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_supervisadas', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='id_orden_produccion',
            field=models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion'),
        ),
    ]
