# Generated by Django 5.2.6 on 2025-10-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_initial'),
        ('productos', '0002_producto_dias_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
