# Generated by Django 5.2.6 on 2025-10-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_ordenproduccion_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_linea_produccion',
            fields=[
                ('id_estado_linea_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_linea_produccion',
            },
        ),
    ]
