# Generated by Django 5.2.6 on 2025-10-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_estado_linea_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaproduccion',
            name='id_estado_linea_produccion',
            field=models.ForeignKey(db_column='id_estado_linea_produccion', default=1, on_delete=django.db.models.deletion.CASCADE, to='produccion.estado_linea_produccion'),
            preserve_default=False,
        ),
    ]
