# Generated by Django 5.2.6 on 2025-10-22 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_lineaproduccion_id_estado_linea_produccion'),
        ('ventas', '0010_direccioncliente_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_orden_venta',
            field=models.ForeignKey(blank=True, db_column='id_orden_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.ordenventa'),
        ),
    ]
