# Generated by Django 5.2.6 on 2025-10-23 23:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_rol_permisos'),
        ('produccion', '0006_ordenproduccion_id_orden_venta'),
        ('productos', '0004_imagenproducto'),
        ('stock', '0006_estadoreservamateria_and_more'),
        ('ventas', '0017_notacredito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrdenProduccion',
            fields=[
                ('id_orden_produccion', models.IntegerField(blank=True, db_index=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_estado_orden_produccion', models.ForeignKey(blank=True, db_column='id_estado_orden_produccion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.estadoordenproduccion')),
                ('id_linea_produccion', models.ForeignKey(blank=True, db_column='id_linea_produccion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.lineaproduccion')),
                ('id_lote_produccion', models.ForeignKey(blank=True, db_column='id_lote_produccion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.loteproduccion')),
                ('id_operario', models.ForeignKey(blank=True, db_column='id_operario', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('id_orden_venta', models.ForeignKey(blank=True, db_column='id_orden_venta', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.ordenventa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.producto')),
                ('id_supervisor', models.ForeignKey(blank=True, db_column='id_supervisor', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'historical orden produccion',
                'verbose_name_plural': 'historical orden produccions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
