# Generated by Django 5.2.6 on 2025-11-01 02:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_historicalordenproduccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoOrdenTrabajo',
            fields=[
                ('id_estado_orden_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Orden de Trabajo',
                'verbose_name_plural': 'Estados de Órdenes de Trabajo',
                'db_table': 'estado_orden_trabajo',
            },
        ),
        migrations.RemoveField(
            model_name='historicalordenproduccion',
            name='id_linea_produccion',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='id_linea_produccion',
        ),
        migrations.AddField(
            model_name='lineaproduccion',
            name='capacidad_por_hora',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='HistoricalOrdenDeTrabajo',
            fields=[
                ('id_orden_trabajo', models.IntegerField(blank=True, db_index=True)),
                ('cantidad_programada', models.IntegerField()),
                ('hora_inicio_programada', models.DateTimeField()),
                ('hora_fin_programada', models.DateTimeField()),
                ('hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('cantidad_producida', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_estado_orden_trabajo', models.ForeignKey(blank=True, db_column='id_estado_orden_trabajo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.estadoordentrabajo')),
                ('id_linea_produccion', models.ForeignKey(blank=True, db_column='id_linea_produccion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.lineaproduccion')),
                ('id_orden_produccion', models.ForeignKey(blank=True, db_column='id_orden_produccion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'historical Orden de Trabajo',
                'verbose_name_plural': 'historical Órdenes de Trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id_orden_trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_programada', models.IntegerField()),
                ('hora_inicio_programada', models.DateTimeField()),
                ('hora_fin_programada', models.DateTimeField()),
                ('hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('cantidad_producida', models.IntegerField(blank=True, null=True)),
                ('id_estado_orden_trabajo', models.ForeignKey(blank=True, db_column='id_estado_orden_trabajo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.estadoordentrabajo')),
                ('id_linea_produccion', models.ForeignKey(db_column='id_linea_produccion', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_de_trabajo', to='produccion.lineaproduccion')),
                ('id_orden_produccion', models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_trabajo', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'orden_de_trabajo',
                'ordering': ['hora_inicio_programada'],
            },
        ),
    ]
