# Generated by Django 5.2.6 on 2025-11-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_estadoordentrabajo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PausaOT',
            fields=[
                ('id_pausa', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('duracion_minutos', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('id_orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='produccion.ordendetrabajo')),
            ],
            options={
                'db_table': 'pausa_orden_trabajo',
            },
        ),
    ]
