# Generated by Django 5.2.6 on 2025-11-07 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_pausaot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNoConformidad',
            fields=[
                ('id_tipo_no_conformidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de No Conformidad',
                'verbose_name_plural': 'Tipos de No Conformidades',
                'db_table': 'tipo_no_conformidad',
            },
        ),
        migrations.RemoveField(
            model_name='noconformidad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='noconformidad',
            name='id_orden_produccion',
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='id_orden_trabajo',
            field=models.ForeignKey(db_column='id_orden_trabajo', default=1, on_delete=django.db.models.deletion.CASCADE, to='produccion.ordendetrabajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='id_tipo_no_conformidad',
            field=models.ForeignKey(db_column='id_tipo_no_conformidad', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='produccion.tiponoconformidad', verbose_name='Tipo de No Conformidad'),
            preserve_default=False,
        ),
    ]
