# Generated by Django 5.2.6 on 2025-11-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_tiponoconformidad_remove_noconformidad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalordendetrabajo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical orden de trabajo', 'verbose_name_plural': 'historical orden de trabajos'},
        ),
        migrations.AlterModelOptions(
            name='ordendetrabajo',
            options={'ordering': ['hora_inicio_programada']},
        ),
        migrations.AlterField(
            model_name='noconformidad',
            name='id_orden_trabajo',
            field=models.ForeignKey(db_column='id_orden_trabajo', on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidades', to='produccion.ordendetrabajo'),
        ),
        migrations.AlterField(
            model_name='noconformidad',
            name='id_tipo_no_conformidad',
            field=models.ForeignKey(db_column='id_tipo_no_conformidad', on_delete=django.db.models.deletion.PROTECT, to='produccion.tiponoconformidad'),
        ),
    ]
