# Generated by Django 5.2.6 on 2025-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_alter_historicalordendetrabajo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordendetrabajo',
            name='produccion_bruta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='produccion_bruta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
