# Generated by Django 5.2.6 on 2025-11-12 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0012_historicalordendetrabajo_produccion_bruta_and_more'),
        ('ventas', '0019_cliente_altura_cliente_calle_cliente_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordenproduccion',
            name='id_orden_venta',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='id_orden_venta',
        ),
        migrations.CreateModel(
            name='OrdenVentaProduccion',
            fields=[
                ('id_orden_venta_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_asignada', models.IntegerField(blank=True, help_text='Cantidad de productos de esta OP asignada a esta OV (opcional)', null=True)),
                ('id_orden_produccion', models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
                ('id_orden_venta', models.ForeignKey(db_column='id_orden_venta', on_delete=django.db.models.deletion.CASCADE, to='ventas.ordenventa')),
            ],
            options={
                'verbose_name': 'Relación Orden de Venta - Orden de Producción',
                'verbose_name_plural': 'Relaciones Orden de Venta - Orden de Producción',
                'db_table': 'orden_venta_produccion',
                'unique_together': {('id_orden_venta', 'id_orden_produccion')},
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='ordenes_venta',
            field=models.ManyToManyField(related_name='ordenes_produccion', through='produccion.OrdenVentaProduccion', to='ventas.ordenventa'),
        ),
    ]
