# Generated by Django 5.2.6 on 2025-11-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_remove_historicalordenproduccion_id_orden_venta_and_more'),
        ('ventas', '0019_cliente_altura_cliente_calle_cliente_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='ordenes_venta',
        ),
        migrations.AddField(
            model_name='historicalordenproduccion',
            name='id_orden_venta',
            field=models.ForeignKey(blank=True, db_column='id_orden_venta', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ventas.ordenventa'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_orden_venta',
            field=models.ForeignKey(blank=True, db_column='id_orden_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.ordenventa'),
        ),
    ]
