# Generated by Django 5.2.6 on 2025-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_remove_ordenproduccion_ordenes_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenproduccion',
            name='fecha_planificada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_planificada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
