# Generated by Django 5.2.6 on 2025-11-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_historicalordenproduccion_fecha_planificada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('horas_reservadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_linea_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_calendario', to='produccion.lineaproduccion')),
                ('id_orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_calendario', to='produccion.ordenproduccion')),
            ],
            options={
                'unique_together': {('id_linea_produccion', 'fecha', 'id_orden_produccion')},
            },
        ),
    ]
