# Generated by Django 5.2.6 on 2025-11-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_calendarioproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioproduccion',
            name='cantidad_a_producir',
            field=models.IntegerField(default=0),
        ),
    ]
