# Generated by Django 5.2.6 on 2025-11-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_calendarioproduccion_cantidad_a_producir'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenproduccion',
            name='fecha_fin_planificada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_fin_planificada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
