# Generated by Django 5.2.6 on 2025-11-16 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_historicalordenproduccion_fecha_fin_planificada_and_more'),
        ('ventas', '0020_historicalordenventa_fecha_entrega_planificada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionPegging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovs_vinculadas', to='produccion.ordenproduccion')),
                ('id_orden_venta_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_vinculadas', to='ventas.ordenventaproducto')),
            ],
            options={
                'unique_together': {('id_orden_produccion', 'id_orden_venta_producto')},
            },
        ),
    ]
