# Generated by Django 5.2.6 on 2025-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0019_ordenproduccionpegging'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordenproduccion',
            name='es_generada_automaticamente',
            field=models.BooleanField(default=False, help_text='True si fue creada por el MRP. False si fue creada manualmente.'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='es_generada_automaticamente',
            field=models.BooleanField(default=False, help_text='True si fue creada por el MRP. False si fue creada manualmente.'),
        ),
    ]
