# Generated by Django 5.2.6 on 2025-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0020_historicalordenproduccion_es_generada_automaticamente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordenproduccion',
            name='es_generada_automaticamente',
            field=models.BooleanField(default=False, help_text='True si fue creada por el MRP. False si fue creada manualmente.', null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='es_generada_automaticamente',
            field=models.BooleanField(default=False, help_text='True si fue creada por el MRP. False si fue creada manualmente.', null=True),
        ),
    ]
