# Generated by Django 5.2.6 on 2025-10-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias_primas', '0003_alter_materiaprima_umbral_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_orden_compra',
            fields=[
                ('id_estado_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_orden_compra',
            },
        ),
        migrations.CreateModel(
            name='orden_compra',
            fields=[
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_entrega_estimada', models.DateField()),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('id_estado_orden_compra', models.ForeignKey(db_column='id_estado_orden_compra', on_delete=django.db.models.deletion.CASCADE, to='compras.estado_orden_compra')),
                ],
            options={
                'db_table': 'orden_compra',
            },
        ),
        migrations.CreateModel(
            name='orden_compra_materia_prima',
            fields=[
                ('id_orden_compra_materia_prima', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_materia_prima', models.ForeignKey(db_column='id_materia_prima', on_delete=django.db.models.deletion.CASCADE, to='materias_primas.materiaprima')),
                ('id_orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, to='compras.orden_compra')),
            ],
            options={
                'db_table': 'orden_compra_materia_prima',
            },
        ),
    ]
