# Generated by Django 5.2.6 on 2025-10-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('materias_primas', '0005_materiaprima_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', default=1, on_delete=django.db.models.deletion.CASCADE, to='materias_primas.proveedor'),
            preserve_default=False,
        ),
    ]
