# Generated by Django 5.2.6 on 2025-10-18 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_orden_compra_id_proveedor'),
        ('materias_primas', '0005_materiaprima_id_proveedor'),
        ('produccion', '0005_lineaproduccion_id_estado_linea_produccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estado_orden_compra',
            new_name='EstadoOrdenCompra',
        ),
        migrations.RenameModel(
            old_name='orden_compra_materia_prima',
            new_name='OrdenCompraMateriaPrima',
        ),
        migrations.RenameModel(
            old_name='orden_compra',
            new_name='OrdenCompra',
        ),
        migrations.CreateModel(
            name='OrdenCompraProduccion',
            fields=[
                ('id_orden_compra_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('id_orden_compra', models.ForeignKey(db_column='id_orden_compra', on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
                ('id_orden_produccion', models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'orden_compra_produccion',
            },
        ),
    ]
