# Generated by Django 5.2.6 on 2025-11-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_historicalordencompra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-id_orden_compra']},
        ),
    ]
