# Generated by Django 5.2.6 on 2025-09-27 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'permiso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='empleados.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='empleados.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': True,
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
