# Generated by Django 5.2.6 on 2025-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_permiso_rolpermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='roles', through='empleados.RolPermiso', to='empleados.permiso'),
        ),
    ]
